apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mw-applicationset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/Raisal-A/helm-charts-values.git  # New repo for values.yaml
              revision: master
              files:
                - path: 'nahdi-mw/*-values.yaml'  # Update path to new location
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{.helm.appName}}'
    spec:
      destination:
        namespace: '{{ .path.filename | replace "-values.yaml" "" }}'  # Dynamically set namespace
        server: 'https://kubernetes.default.svc'  # Static server value
      project: production
      source:
        helm:
          valueFiles:
            - '{{ .path.path }}'  # Using the matched values.yaml file
        path: 'nahdi-mw'  # Path to your Helm chart (static in this case)
        repoURL: https://github.com/Raisal-A/helm-charts-testing-new.git  # Original repo for Helm chart
        targetRevision: master
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
